version: '3'
services:
  linebot:
    image: toc:latest
    container_name: linebot
    restart: always
    environment: 
        - LINE_CHANNEL_ACCESS_TOKEN
        - LINE_CHANNEL_SECRET
        - FLASK_ENV
    ports:
        - "5000:5000"